name: eclair-lang
version: 0.1.0.0
#synopsis:
#description:
homepage: https://github.com/luc-tielen/eclair-lang
license: BSD3
author: Luc Tielen
maintainer: luc.tielen@gmail.com
copyright: Luc Tielen, 2021
category: Web
extra-source-files:
  - README.md

dependencies:
  - base >= 4.7 && < 5
  - protolude == 0.3.0
  - extra == 1.*
  - text == 1.*
  - vector == 0.12.*
  - containers == 0.*
  - transformers == 0.*
  - mtl == 2.*
  - exceptions == 0.10.*
  - lens == 4.*
  - prettyprinter == 1.*
  - souffle-haskell == 3.0.0
  - megaparsec == 9.*
  - recursion-schemes == 5.*
  - algebraic-graphs == 0.*

default-extensions:
  - NoImplicitPrelude
  - OverloadedStrings
  - LambdaCase
  - ViewPatterns
  - TypeFamilies
  - DeriveFunctor
  - DeriveFoldable
  - DeriveTraversable
  - ScopedTypeVariables

ghc-options:
  - -fhide-source-paths
  - -fno-show-valid-hole-fits
  - -fno-sort-valid-hole-fits
cxx-options:
  - -std=c++20
  - -D__EMBEDDED_SOUFFLE__
cxx-sources:
  - cbits/*.cpp

when:
  - condition: os(darwin)
    extra-libraries: c++

library:
  source-dirs: lib
  cxx-sources: cbits/*.cpp
  cxx-options:
    - -Wall
  when:
    - condition: os(linux)
      extra-libraries: stdc++

executables:
  ec:
    main: Main.hs
    source-dirs: src
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      # - -Wall
    dependencies:
      - base >= 4.7 && < 5
      - eclair-lang

tests:
  eclair-test:
    main: test.hs
    source-dirs: tests
    dependencies:
      - hspec >= 2.6.1 && < 3.0.0
      - hspec-hedgehog == 0.*
      - hedgehog == 1.*
      - filepath == 1.*
      - neat-interpolation == 0.*
      - eclair-lang
