name: "Build"
on: [push, pull_request]
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v2.4.0
      - name: Build and test
        run: |
          set -eo pipefail
          docker build -f Dockerfile . -t eclair | tee eclair-lang-${{matrix.os}}.log
          docker run --rm eclair bash -c "make test" | tee -a eclair-lang-${{matrix.os}}.log
      - name: Upload logs
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: eclair-lang-${{matrix.os}}.log
          path: eclair-lang-${{matrix.os}}.log
